name: nightly
permissions:
  contents: write
on:
  schedule:
    - cron: '0 10 * * 1-5'
  push:
    paths:
      - '.github/workflows/nightly.yml'
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v7 
      with: 
        script: |
          const releases = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          for (const release of releases.data) {
            if (release.tag_name === 'nightly') {
              await github.rest.repos.deleteRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.id,
              });
            }
          }
          await github.rest.git.deleteRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `tags/nightly`,
          });
  nightly:
    needs: init
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: windows-x86_64
          - os: macos-14
            name: macos-arm64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actboy168/setup-luamake@master
    - uses: actions/checkout@v4
      with:
        submodules: true
    - run: luamake all -mode release
    - uses: actboy168/action-zip@main
      id: zip
      with:
        name: ant-${{ matrix.name }}
        path: |
          bin/
          !bin/**/*.a
          !bin/**/*.exp
          !bin/**/*.lib
          !bin/**/*.ilk
          engine/
          pkg/
          test/
          tools/
          README.md
          LICENSE
    - uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        name: nightly
        tag_name: nightly
        fail_on_unmatched_files: true
        files: ${{  steps.zip.outputs.output }}
